apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/instance: 00-infra
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/infra/proxy/letsencrypt
    repoURL: git@github.com:Crisu1710/k8s-home.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ovh
  namespace: argocd
  labels:
    app.kubernetes.io/instance: 00-infra
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager-webhook-ovh
    repoURL: https://aureq.github.io/cert-manager-webhook-ovh
    targetRevision: 0.4.2
    helm:
      values: |-
        groupName: acme.domain.tld
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
