apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud
  namespace: owncloud
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: passwd
    template:
      engineVersion: v2
      data:
        db-password: "{{ .db }}"
        user-password: "{{ .user }}"
  data:
    - secretKey: db
      remoteRef:
        key: secret/k8s
        property: OC_DB_PASSWD
    - secretKey: user
      remoteRef:
        key: secret/k8s
        property: OC_USER_PASSWD
