apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    app.kubernetes.io/instance: 00-infra
spec:
  project: default
  source:
    repoURL: 'git@github.com:Crisu1710/k8s-home.git'
    path: manifests/infra/proxy/nginx
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
