apiVersion: v1
kind: Service
metadata:
  name: nfs
  namespace: storage
spec:
  type: ClusterIP
  clusterIP: 10.102.90.104
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
