apiVersion: v1
kind: Service
metadata:
  name: owncloud
  namespace: owncloud
  labels:
    environment: extern
    app: owncloud
spec:
  selector:
    app: owncloud
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8088
      name: web
