apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: "10.102.90.104"
            - name: NFS_PATH
              value: "/"
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.102.90.104
            path: "/exports"
