apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deploy
  namespace: nextcloud
  labels:
    environment: extern
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
      annotations:
        linkerd.io/inject: disabled
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nextcloud-db
                topologyKey: topology.kubernetes.io/hostname
              weight: 100
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: nextcloud-conf-pvc
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
      containers:
        - name: nextcloud
          image: nextcloud:30.0.4
          volumeMounts:
            - name: vol
              mountPath: /var/www/html
            - name: data
              mountPath: /var/www/data
          ports:
            - containerPort: 80
              name: web
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "cloud.domain.tld"
          resources:
            requests:
              memory: "170Mi"
              cpu: "20m"
            #limits:
            #  memory: "300Mi"
            #  cpu: "30m"
