apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-tld-cert
  namespace: cert-manager
spec:
  renewBefore: 360h0m0s #15d
  secretName: domain-tld-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: "*.domain.tld"
  dnsNames:
    - "*.domain.tld"
