apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ovh-credentials
    template:
      engineVersion: v2
      data:
        applicationSecret: "{{ .applicationSecret }}"
        applicationKey: "{{ .applicationKey }}"
        consumerKey: "{{ .consumerKey }}"
  data:
    - secretKey: applicationSecret
      remoteRef:
        key: secret/k8s
        property: OVH_APP_SECRET
    - secretKey: applicationKey
      remoteRef:
        key: secret/k8s
        property: OVH_APP_KEY
    - secretKey: consumerKey
      remoteRef:
        key: secret/k8s
        property:  OVH_CONSUMER_KEY
