apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-db
  namespace: grafana
spec:
  replicas: 1
  serviceName: grafana-db-hs
  selector:
    matchLabels:
      app: grafana-db
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: grafana-db
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: grafana-db
        - name: backup
          persistentVolumeClaim:
            claimName: grafana-db-backup
      containers:
        - name: postgres
          image: postgres:17.3
#          securityContext:
#            runAsUser: 999
#          args:
#            - pg_resetwal
#            - /var/lib/postgresql/data
          volumeMounts:
            - name: vol
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: grafana
            - name: POSTGRES_USER
              value: grafana
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-passwd
        - name: postgres-backup
          image: ghcr.io/crisu1710/docker-pg_dump:0.1.0
          args: ["dump-cron"]
          volumeMounts:
            - name: backup
              mountPath: /dump
          env:
            - name: PGUSER
              value: "postgres"
            - name: PGHOST
              value: "localhost"
            - name: PGDB
              value: "grafana"
            - name: CRON_SCHEDULE
              value: "0 1 * * *"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-passwd
