kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
- custom-default-backend

labels:
- includeSelectors: true
  pairs:
    environment: reverse-proxy
patches:
- path: service.yaml
  target:
    kind: Service
    name: ingress-nginx-controller
    version: v1
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: ingress-nginx-controller
    version: v1
- path: ingressclass.yaml
  target:
    kind: IngressClass
    name: nginx
    version: v1
