apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.213.100
  labels:
    environment: extern
    app: pihole
spec:
  externalTrafficPolicy: Local
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - targetPort: dns
      port: 53
      name: dns
      protocol: UDP
    - targetPort: dns-tcp
      port: 53
      protocol: TCP
      name: dns-tcp
    - targetPort: web
      port: 8333
      name: web
