apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-errors
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: error-html
              mountPath: /var/www/html/error-page.html
              subPath: error-page.html
          resources:
            requests:
              memory: "6Mi"
              cpu: "1m"
            limits:
              memory: "10Mi"
              cpu: "1m"
          ports:
          - containerPort: 80
      volumes:
        - name: conf
          configMap:
            name: nginx-error
            items:
              - key: default.conf
                path: default.conf
        - name: error-html
          configMap:
            name: error-html
            items:
              - key: error-page.html
                path: error-page.html
