apiVersion: v1
kind: Service
metadata:
  name: matrix-db-hs
  namespace: matrix
  labels:
    environment: intern
    app: matrix-db
spec:
  selector:
    app: matrix-db
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
