apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paperless-redis-statefulset
  namespace: paperless
spec:
  replicas: 1
  serviceName: paperless-redis-hs
  selector:
    matchLabels:
      app: paperless-redis
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: paperless-redis
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - paperless
                topologyKey: topology.kubernetes.io/hostname
              weight: 100
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: paperless-redis-pvc
      containers:
        - name: redis
          image: docker.io/library/redis:8
          volumeMounts:
            - name: vol
              mountPath: /data
          ports:
            - containerPort: 6379
