apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8987
      name: web
