apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mayastor
  namespace: argocd
  labels:
    app.kubernetes.io/instance: 00-infra
spec:
  destination:
    namespace: storage
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mayastor
    repoURL: https://openebs.github.io/mayastor-extensions/
    targetRevision: 2.2.0
    helm:
      parameters:
      - name: loki-stack.enabled
        value: "false"
      - name: loki-stack.loki.config.compactor.retention_enabled
        value: "false"
      - name: loki-stack.loki.enabled
        value: "false"
      - name: loki-stack.loki.persistence.enabled
        value: "false"
      - name: loki-stack.promtail.enabled
        value: "false"
      - name: etcd.persistence.storageClass
        value: "manual"
      - name: loki-stack.persistence.storageClass
        value: "manual"
      - name: etcd.replicaCount
        value: "1"
      values: |-
        etcd:
          ​replicaCount: 1
          nodeSelector:
            kubernetes.io/arch: amd64
  syncPolicy:
    #automated: {}
    syncOptions:
      - CreateNamespace=true
