apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db-hs
  namespace: nextcloud
  labels:
    environment: intern
    app: nextcloud-db
spec:
  selector:
    app: nextcloud-db
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
