apiVersion: v1
kind: Service
metadata:
  name: paperless-redis-hs
  namespace: paperless
  labels:
    environment: intern
    app: paperless-redis
spec:
  selector:
    app: paperless-redis
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
