apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 00-automation/apps/namespaces
    repoURL: git@github.com:Crisu1710/k8s-home.git
    targetRevision: main
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
