apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mqtt
  namespace: homeassistant
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mqtt
    template:
      engineVersion: v2
      data:
        password.txt: "{{ .mqttpasswd }}"
  data:
    - secretKey: mqttpasswd
      remoteRef:
        key: secret/k8s
        property: MQTT_PASSWD
