apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coturn-conf
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: coturn-conf
    template:
      engineVersion: v2
      data:
        turnserver.conf: |
          log-file=stdout
          listening-port=5349
          min-port=49160
          max-port=49200
          use-auth-secret
          static-auth-secret="{{ .staticAuthSecret }}"
          realm=turn.domain.tld:5349
          no-cli
          cert=/var/run/secret/tls.crt
          pkey=/var/run/secret/tls.key
          prometheus
  data:
    - secretKey: staticAuthSecret
      remoteRef:
        key: secret/k8s
        property: TURN_SECRET
