apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
      storage.k8s.io/name: nfs
      storage.k8s.io/part-of: kubernetes-complete-reference
      storage.k8s.io/created-by: ssbostan
  name: grafana-db
  namespace: grafana
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
      storage.k8s.io/name: nfs
      storage.k8s.io/part-of: kubernetes-complete-reference
      storage.k8s.io/created-by: ssbostan
  name: grafana-db-backup
  namespace: grafana
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
