apiVersion: v1
kind: Service
metadata:
  name: grafana-db-hs
  namespace: grafana
  labels:
    environment: intern
    app: grafana-db
spec:
  selector:
    app: grafana-db
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
