apiVersion: v1
kind: Service
metadata:
  name: paperless-db-hs
  namespace: paperless
  labels:
    environment: intern
    app: paperless-db
spec:
  selector:
    app: paperless-db
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
