apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: passwd
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/k8s
        property: STD_DB_PASSWD
